### ISSUE TITLE
Staging is broken

### ISSUE THREAD

**Issue by maser** [eurucamp/call4papers#100]
```
thin Unexpected error while processing request: Missing `secret_token` and `secret_key_base` for 'staging' environment, set these values in `config/secrets.yml`                                              
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:520:in `validate_secret_key_config!'                            
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:246:in `env_config'                                             
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:514:in `call'                                                        
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'                                                   
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'                                                
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'                                             
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'                                          
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'                                                         
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'                                                   
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'                                                       
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'                                                  
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run_machine'                                             
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.4/lib/eventmachine.rb:187:in `run'                                                     
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'                                                      
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'                                                            
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'                                             
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'                                                      
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'                                                             
thin    /home/app/app/releases/cf612bebca09890043b654f12b17a9c04b829d31/vendor/bundle/ruby/2.2.0/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'                                                             
thin    /home/app/app/releases/39ce1c12f49ae4a984053b8f31d2c6b1079c5cc8/vendor/bundle/bin/thin:16:in `load'                                                                                                   
thin    /home/app/app/releases/39ce1c12f49ae4a984053b8f31d2c6b1079c5cc8/vendor/bundle/bin/thin:16:in `<main>'
```

**Comment by maser** [comment]
Haha, GitHub believes in me :)

**Comment by maser** [comment]
It’s not fixed.

**Comment by moonglum** [comment]
Should we reopen then?

**Comment by maser** [comment]
Oh, sorry, I fixed it with the help of @bascht and forgot to update the issue.

**Comment by moonglum** [comment]
Ok, great!
